project_name: legitify

before:
  hooks:
    - go mod verify
    - go mod tidy

builds:
  - id: legitify
    binary: '{{ .ProjectName }}'
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s'
      - '-w'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Name={{ .ProjectName }}'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Version={{ .Version }}'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    targets:
      - 'linux_amd64'

archives:
  - builds:
      - legitify

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: 'sha256'

release:
  draft: false
