project_name: legitify

before:
  hooks:
    - go mod verify
    - go mod tidy

builds:
  - id: legitify
    binary: '{{ .ProjectName }}'
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s'
      - '-w'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Name={{ .ProjectName }}'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Version={{ .Version }}'
      - '-X=github.com/Legit-Labs/legitify/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    targets:
      - 'darwin_amd64'
      - 'darwin_arm64'
      - 'linux_amd64'
      - 'linux_arm64'
    hooks:
      post: sh -c "if [ '{{ .Ext }}' = '.exe' ] ; then osslsigncode sign -certs /tmp/legit_signature.crt -key /tmp/legit_signature.key -in {{ .Path }} -out {{ .Path }}_signed ; rm {{ .Path }} ; mv {{ .Path }}_signed {{ .Path }} ; fi"

archives:
  - builds:
      - legitify
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA512SUMS'
  algorithm: 'sha512'

release:
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
