# This is the default behavior, will analyze the organization from which the action is running from.
name: Legitify Analyze
on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Legitify Action
        uses: gal-legit/legitify@main # it is recommended to use a specific commit hash
        with:
          github_token: ${{ secrets.GAL_PAT }}
            repositories: Legit-Labs/.github,Legit-Labs/3rd_party_dependency_calc,Legit-Labs/HelloWorld,Legit-Labs/action-download-artifact,Legit-Labs/correlation-poc,Legit-Labs/detect-workflow,Legit-Labs/gal-testing-legitify,Legit-Labs/gh-public-events-analyzer,Legit-Labs/gitoops-fork,Legit-Labs/goreleaser,Legit-Labs/goreleaser-action,Legit-Labs/jupyter-notebooks,Legit-Labs/legit-ascend,Legit-Labs/legit-attestation,Legit-Labs/legit-attestation-uploader,Legit-Labs/legit-k8s-ac,Legit-Labs/legit-oidc,Legit-Labs/legit-provenance-action,Legit-Labs/legit-provenance-generator,Legit-Labs/legit-provenance-uploader,Legit-Labs/legit-provenance-verifier,Legit-Labs/legit-registry-tools,Legit-Labs/legit-remote-provenance,Legit-Labs/legit-remote-provenance-server,Legit-Labs/legit-score,Legit-Labs/legit-score-verifier,Legit-Labs/legit-verify-attestation,Legit-Labs/legitify,Legit-Labs/legitify-github-action-demo,Legit-Labs/legitify-private-archived,Legit-Labs/research-interview-question,Legit-Labs/research-ops,Legit-Labs/research-scripts,Legit-Labs/scm-collectors-standalone,Legit-Labs/scorecard,Legit-Labs/software-supply-chain-security-glossary,Legit-Labs/ssc-vulnerability-db,Legit-Labs/tag-security,Legit-Labs/test-action,Legit-Labs/test-ghcr-npm-scopes
